const articles = [
  {
    slug: 'pourquoi-creer-un-site-web-pour-son-activite',
    title: 'Créer un site web professionnel : méthode, SEO et erreurs à éviter',
    image: '/assets/img/article-site-web.svg',
    excerpt: 'Un guide complet pour transformer un site web en véritable outil commercial : stratégie, arborescence, technique, référencement naturel et conversion.',
    seo: 'Créer un site web professionnel : guide complet SEO et stratégie',
    keywords: 'création site web, site vitrine professionnel, SEO, référencement naturel, site internet entreprise',
    body: `<p>Créer un site web ne consiste pas seulement à choisir une couleur, ajouter quelques pages et publier une adresse. Un bon site est un outil de visibilité, de confiance et de conversion. Il doit répondre à une question simple : que doit pouvoir faire le visiteur après avoir compris votre activité ? Appeler, demander un devis, réserver, acheter ou vous comparer à une autre entreprise ?</p><h2>Commencer par l'objectif, pas par le design</h2><p>Avant de parler de typographie ou d'animation, définissez une action principale. Pour un artisan, ce sera souvent la demande de devis. Pour un professionnel de service, ce peut être la prise de rendez-vous. Pour une entreprise locale, l'itinéraire et le téléphone peuvent être prioritaires.</p><div class="article-diagram"><strong>Parcours utile</strong><span>Recherche Google</span><i>→</i><span>Page adaptée</span><i>→</i><span>Preuve</span><i>→</i><span>Contact</span></div><h2>Construire une arborescence compréhensible</h2><p>Une structure efficace reste généralement courte : Accueil, Prestations, À propos, Articles et Contact. Chaque page doit avoir un rôle propre et une intention de recherche identifiable. Une page “création de site internet à Brest” ne doit pas être un doublon artificiel d'une page “site vitrine”. Elle doit apporter un angle local, des exemples et une réponse spécifique.</p><ul><li>Une page = une intention principale.</li><li>Un titre H1 unique, précis et naturel.</li><li>Des sous-titres H2 qui répondent aux questions réelles.</li><li>Un appel à l'action visible sans forcer le visiteur.</li></ul><h2>Les fondations techniques du référencement</h2><p>Le SEO technique aide les moteurs à comprendre et à charger votre site. Il comprend le HTML sémantique, les balises title et description, les URL lisibles, les données structurées, le sitemap, le fichier robots.txt et la performance mobile. Un site rapide ne remplace pas un contenu utile, mais un site lent peut empêcher ce contenu d'être apprécié.</p><pre class="article-code"><code>&lt;title&gt;Création de site web à Brest | Thibault Dubois&lt;/title&gt;
&lt;meta name="description" content="Sites web rapides et optimisés pour les entreprises du Finistère."&gt;</code></pre><h2>Le contenu qui mérite d'être lu</h2><p>Un texte SEO efficace ne répète pas un mot-clé vingt fois. Il explique, compare, donne des exemples et assume un point de vue. Expliquez ce qu'est un hébergement, pourquoi un formulaire abandonne des prospects ou comment choisir entre un site statique et une application web. Ces réponses attirent des visiteurs qui ont déjà un vrai besoin.</p><h2>Mesurer et améliorer après la mise en ligne</h2><p>La mise en ligne est le début du travail. Observez les pages consultées, les recherches qui amènent les visiteurs, les clics sur le téléphone et les demandes de devis. Une page qui attire du trafic mais ne génère aucun contact mérite peut-être une meilleure preuve, un texte plus clair ou un formulaire plus court.</p><h2>Les erreurs fréquentes</h2><p>Les erreurs les plus coûteuses sont souvent simples : un site sans appel à l'action, des textes copiés, une navigation pensée uniquement pour ordinateur, des images trop lourdes, des coordonnées difficiles à trouver ou des promesses impossibles à vérifier. La technique doit servir la clarté, pas la masquer.</p><div class="article-tip"><strong>À retenir :</strong> un site professionnel relie une intention de recherche à une action claire, avec un contenu utile et une base technique solide.</div>`,
    faq: [{ question: 'Combien coûte la création d’un site web ?', answer: 'Le prix dépend du nombre de pages, du contenu, des fonctionnalités et du niveau d’accompagnement. Un devis détaillé permet de chiffrer le besoin ligne par ligne.' }, { question: 'Combien de temps faut-il pour créer un site ?', answer: 'Un site vitrine peut être préparé en quelques semaines lorsque les contenus et validations sont disponibles. Une application avec espace client ou back-office demande davantage de conception et de tests.' }]
  },
  {
    slug: 'chatbot-personnalise-pour-entreprise',
    title: 'Chatbot personnalisé pour entreprise : conception, données et limites',
    image: '/assets/img/article-chatbot.svg',
    excerpt: 'Comment concevoir un chatbot utile, fiable et réellement adapté à vos clients, de la base de connaissances aux demandes de devis.',
    seo: 'Chatbot personnalisé pour entreprise : guide technique et usages',
    keywords: 'chatbot personnalisé, chatbot entreprise, assistant IA, automatisation relation client',
    body: `<p>Un chatbot professionnel n'est pas simplement une fenêtre de discussion ajoutée à un site. C'est une interface qui doit comprendre un contexte, répondre avec les bonnes informations et savoir passer la main lorsqu'une demande dépasse son périmètre. La qualité vient moins de l'effet “intelligent” que du travail de conception qui l'entoure.</p><h2>Définir les missions du chatbot</h2><p>Commencez par une liste de cas d'usage concrets : présenter les prestations, répondre aux questions fréquentes, orienter vers une page, recueillir les coordonnées ou préparer une demande de devis. Un périmètre clair réduit les réponses vagues et facilite les tests.</p><div class="article-diagram"><strong>Architecture simple</strong><span>Visiteur</span><i>→</i><span>Interface chat</span><i>→</i><span>API sécurisée</span><i>→</i><span>Réponse contrôlée</span></div><h2>La base de connaissances est déterminante</h2><p>Le chatbot doit s'appuyer sur des informations à jour : tarifs indicatifs, zones d'intervention, délais, services, conditions et moyens de contact. Une information absente ne doit pas être inventée. Le système doit pouvoir dire qu'il ne sait pas et proposer un échange humain.</p><h2>Une architecture qui protège les clés</h2><p>La clé du fournisseur d'IA ne doit jamais se trouver dans le JavaScript envoyé au navigateur. Le navigateur envoie le message à votre serveur, le serveur applique les limites, ajoute les consignes, appelle le fournisseur puis renvoie une réponse filtrée.</p><pre class="article-code"><code>Navigateur → /api/chat → validation et rate limit
                         ↓
                   fournisseur IA
                         ↓
                  réponse au visiteur</code></pre><h2>Les garde-fous utiles</h2><ul><li>Limiter la taille des messages et le nombre de requêtes.</li><li>Ne jamais transmettre inutilement des données personnelles.</li><li>Valider côté serveur toute action commerciale proposée par le modèle.</li><li>Prévoir un contact humain et un formulaire classique.</li><li>Journaliser les erreurs sans enregistrer les conversations sensibles en clair.</li></ul><h2>Un chatbot qui convertit sans être agressif</h2><p>Une bonne conversation réduit l'incertitude. Elle peut demander le type de projet, le délai et le budget uniquement lorsque cela aide à préparer un échange. Le bouton de devis doit apparaître au bon moment, pas après chaque phrase. La confiance vient d'une réponse précise et d'une sortie simple.</p><h2>Comment mesurer sa valeur</h2><p>Suivez les ouvertures, les conversations engagées, les demandes de devis et les abandons. Ne mesurez pas seulement le nombre de messages : une conversation courte qui mène à une demande qualifiée peut être plus utile qu'une longue discussion sans suite.</p><div class="article-tip"><strong>À retenir :</strong> un chatbot personnalisé est un petit produit logiciel : il nécessite un périmètre, des données fiables, une sécurité serveur et un suivi dans le temps.</div>`,
    faq: [{ question: 'Un chatbot peut-il remplacer un professionnel ?', answer: 'Non. Il peut répondre aux questions répétitives et préparer une demande, mais un professionnel doit rester disponible pour les cas particuliers et la validation commerciale.' }, { question: 'Les messages sont-ils sécurisés ?', answer: 'Les clés doivent rester côté serveur, les données collectées doivent être limitées au nécessaire et les services utilisés doivent être indiqués dans les mentions légales.' }]
  },
  {
    slug: 'ux-ui-difference-experience-interface',
    title: 'UX et UI : concevoir un site agréable, accessible et efficace',
    image: '/assets/img/article-ux-ui.svg',
    excerpt: 'UX, UI, accessibilité et performance : les principes concrets qui rendent une interface compréhensible et agréable à utiliser.',
    seo: 'UX UI : guide pratique pour concevoir un site efficace et accessible',
    keywords: 'UX UI, expérience utilisateur, interface utilisateur, accessibilité web, design site web',
    body: `<p>UX et UI sont souvent associés, mais ils répondent à deux questions différentes. L'UX s'intéresse à l'expérience et au parcours : l'utilisateur comprend-il quoi faire ? L'UI s'intéresse à l'interface : les boutons, les textes et les états visuels rendent-ils cette action évidente ? Une belle interface qui égare ses visiteurs n'est pas une bonne expérience.</p><h2>L'UX commence par les besoins</h2><p>Interrogez les objectifs du visiteur, ses hésitations et les informations nécessaires avant une décision. Une page de service doit répondre au besoin avant de chercher à impressionner. Les contenus peuvent ensuite être organisés en parcours : comprendre, vérifier, agir.</p><div class="article-diagram"><strong>Une page efficace</strong><span>Promesse</span><i>→</i><span>Preuves</span><i>→</i><span>Détails</span><i>→</i><span>Action</span></div><h2>L'UI crée une hiérarchie visuelle</h2><p>La couleur ne doit pas être le seul signal. La taille, l'espacement, le contraste et la position indiquent ce qui est important. Un bouton principal doit se distinguer d'un lien secondaire, et un champ invalide doit expliquer comment corriger l'erreur.</p><h2>Penser mobile dès la conception</h2><p>Sur mobile, la largeur est réduite, le clavier occupe parfois une partie de l'écran et les interactions au doigt demandent de l'espace. Les titres doivent pouvoir passer à la ligne, les boutons doivent rester atteignables et les tableaux complexes doivent proposer une lecture adaptée.</p><h2>Accessibilité : une exigence utile à tous</h2><ul><li>Un contraste suffisant entre le texte et le fond.</li><li>Des labels associés aux champs, pas seulement des placeholders.</li><li>Un ordre de navigation utilisable au clavier.</li><li>Des alternatives textuelles pour les images importantes.</li><li>Des messages d'erreur compréhensibles et placés près du champ concerné.</li></ul><pre class="article-code"><code>&lt;label for="email"&gt;Votre adresse email&lt;/label&gt;
&lt;input id="email" type="email" autocomplete="email" required&gt;</code></pre><h2>Performance et perception</h2><p>Un écran qui apparaît progressivement peut sembler plus lent qu'une page simple qui devient utile immédiatement. Réduisez les images, évitez les scripts inutiles et donnez une réponse visible lors d'une action. Les Core Web Vitals sont techniques, mais leur objectif reste humain : charger, répondre et rester stable.</p><h2>Tester plutôt que deviner</h2><p>Demandez à une personne de trouver une prestation ou de demander un devis sans l'aider. Observez les hésitations. Les statistiques peuvent signaler un problème, mais une observation directe explique souvent pourquoi le bouton n'est pas trouvé.</p><div class="article-tip"><strong>À retenir :</strong> l'UX organise la décision et l'UI la rend visible. Les deux doivent servir la compréhension avant la décoration.</div>`,
    faq: [{ question: 'Quelle est la différence entre UX et UI ?', answer: 'L’UX concerne le parcours, les besoins et la facilité d’utilisation. L’UI concerne l’apparence et les états de l’interface. Ils se complètent.' }, { question: 'Pourquoi penser à l’accessibilité ?', answer: 'Une interface accessible est plus robuste pour les personnes en situation de handicap, mais aussi pour les usages mobiles, les connexions lentes et les contextes difficiles.' }]
  },
  {
    slug: 'hebergement-nom-domaine-email-professionnel',
    title: 'Hébergement, nom de domaine et email professionnel : le guide technique',
    image: '/assets/img/article-hebergement.svg',
    excerpt: 'DNS, HTTPS, déploiement et email : comprendre les briques techniques qui rendent une présence en ligne fiable.',
    seo: 'Hébergement, nom de domaine et email professionnel : guide technique',
    keywords: 'hébergement web, nom de domaine, DNS, HTTPS, email professionnel, Railway',
    body: `<p>Un site professionnel repose sur plusieurs services qui sont souvent mélangés. Le nom de domaine est l'adresse, l'hébergement exécute ou sert le site, et le DNS relie les deux. L'email professionnel utilise lui aussi le domaine, mais avec des enregistrements spécifiques.</p><h2>Nom de domaine et DNS</h2><p>Le domaine est une identité facile à mémoriser. Le DNS indique où trouver les services : un enregistrement A ou CNAME peut diriger le site, tandis que les enregistrements MX indiquent les serveurs email. Une modification DNS peut demander du temps avant d'être visible partout.</p><div class="article-diagram"><strong>Résolution d'une adresse</strong><span>nomdedomaine.fr</span><i>→</i><span>DNS</span><i>→</i><span>serveur web</span></div><h2>Pourquoi HTTPS est indispensable</h2><p>HTTPS chiffre les échanges entre le navigateur et le serveur. Il protège les formulaires, rassure les visiteurs et évite les alertes de sécurité. Un certificat ne corrige pas un site mal sécurisé, mais son absence est un signal immédiatement négatif.</p><h2>Choisir un hébergement</h2><p>Un site statique, une application Node.js et une base de données n'ont pas les mêmes besoins. Il faut regarder la disponibilité, les sauvegardes, les logs, les variables d'environnement, la possibilité de déployer depuis Git et la conservation des données.</p><pre class="article-code"><code>Code source → déploiement → application
                              ↓
                         base de données
                              ↓
                         volume persistant</code></pre><h2>Railway et les données persistantes</h2><p>Railway peut exécuter le serveur et fournir un environnement adapté aux variables secrètes. Une base SQLite doit toutefois être placée sur un volume persistant, sinon un redéploiement peut supprimer les données. Pour un projet qui grandit, une base PostgreSQL peut devenir plus adaptée.</p><h2>Email professionnel et délivrabilité</h2><p>Une adresse comme contact@votredomaine.fr renforce la cohérence de la marque. Pour que les messages arrivent correctement, configurez SPF, DKIM et DMARC chez votre fournisseur email. Un email envoyé depuis un domaine non authentifié peut finir en spam, même si le code fonctionne.</p><h2>La checklist avant mise en ligne</h2><ul><li>Domaine renouvelable et coordonnées du titulaire à jour.</li><li>HTTPS actif sur toutes les pages.</li><li>Secrets uniquement dans les variables de l'hébergeur.</li><li>Sauvegarde et restauration de la base testées.</li><li>Email d'envoi authentifié avec SPF/DKIM.</li><li>Mentions légales complétées avec l'hébergeur réel.</li></ul><div class="article-tip"><strong>À retenir :</strong> une mise en ligne fiable est un ensemble : domaine, DNS, HTTPS, serveur, stockage et email doivent être pensés ensemble.</div>`,
    faq: [{ question: 'Quelle différence entre domaine et hébergement ?', answer: 'Le domaine est l’adresse mémorisable du site. L’hébergement fournit l’espace et les serveurs qui servent les fichiers ou exécutent l’application.' }, { question: 'Pourquoi un volume persistant est-il nécessaire ?', answer: 'Il conserve la base et les fichiers lorsque le service est redéployé. Sans stockage persistant, des données locales peuvent disparaître.' }]
  }
];
module.exports = articles;
